### ISSUE TITLE
Exit code 1 and ffmpeg not found

### ISSUE THREAD

**Issue by FaisalRehman234** [songs18/m3u8_To_MP4#6]
I have already installed ffmpeg and all requitements but showing error code 1

"C:\Users\faisa\Documents\Pycharm Projects\Youtube Views\venv\Scripts\python.exe" "C:/Users/faisa/Documents/Pycharm Projects/Youtube Views/main.py"
2022-03-05 20:38:00,870 | WARNING | NOT FOUND FFMPEG!
2022-03-05 20:38:00,870 | INFO | Compressing into tar.bz2 is only supported

summary
m3u8_uri: http://videoserver.com/playlist.m3u8;
max_retry_times: 3;
tmp_dir: C:\Users\faisa\AppData\Local\Temp\m3u8_3881882585;
mp4_file_path: ./m3u8_To_Mp4.mp4;

2022-03-05 20:38:01,433 | INFO | Resolved available hosts:
2022-03-05 20:38:01,433 | INFO | 52.128.23.153:80
Traceback (most recent call last):
  File "C:\Users\faisa\Documents\Pycharm Projects\Youtube Views\main.py", line 7, in <module>
    m3u8_To_MP4.multithread_download('http://videoserver.com/playlist.m3u8')
  File "C:\Users\faisa\Documents\Pycharm Projects\Youtube Views\venv\lib\site-packages\m3u8_To_MP4\__init__.py", line 75, in multithread_download
    crawler.fetch_mp4_by_m3u8_uri(True)
  File "C:\Users\faisa\Documents\Pycharm Projects\Youtube Views\venv\lib\site-packages\m3u8_To_MP4\v2_abstract_processor.py", line 250, in fetch_mp4_by_m3u8_uri
    key_segments_pairs = self._filter_ads_ts(key_segments_pairs)
  File "C:\Users\faisa\Documents\Pycharm Projects\Youtube Views\venv\lib\site-packages\m3u8_To_MP4\v2_abstract_processor.py", line 193, in _filter_ads_ts
    self.longest_common_subsequence = path_helper.longest_common_subsequence([segment_uri for _, segment_uri in key_segments_pairs])
  File "C:\Users\faisa\Documents\Pycharm Projects\Youtube Views\venv\lib\site-packages\m3u8_To_MP4\helpers\path_helper.py", line 40, in longest_common_subsequence
    num_shortest_segment_absolute_url_length = min(len(url) for url in segment_absolute_urls)
ValueError: min() arg is an empty sequence

Process finished with exit code 1

**Comment by songs18** [comment]
Hi,

First, m3u8_To_Mp4 runs "ffmpeg -version" to determine whether ffmpeg is available in the system. From the post traceback, it is possible that you did not add ffmpeg to the system path correctly.

Second, the input m3u8_url needs to be valid. Currently, the program does not check any ts fragments, so you need to check the validity of the m3u8_url.

Thank you for your interest in my project.

**Comment by FaisalRehman234** [comment]
Thanks songs18. My problem is now solved...
