### ISSUE TITLE
Error: cannot find file

### ISSUE THREAD

**Issue by yaumi123** [songs18/m3u8_To_MP4#8]
I'm using multithread_download() with url. 
Downloading goes well in console with progress %. When it's done, it shows error 'cannot find file path './m3u8_To_Mp4.mp4'.
I tried create a file './m3u8_To_Mp4.mp4' advancedly but it still doesn't work.
Did I miss something?

**Comment by yaumi123** [comment]
直接说中文了
发现是_merge_to_mp4_by_ffmpeg()这个函数的问题，subprocess没有完成，然后在外面下载函数结尾打印下载信息的时候就找不到文件了。
我debug下，把cmd命令复制出来 在cmd里手动执行，是可以成功拼接mp4文件并置入指定目录的。
但是程序中的subprocess.Popen()并没有执行这个ffmepg指令。是否需要配置什么东西？

**Comment by yaumi123** [comment]
原来是在python环境中 没法使用ffmpeg（系统环境因为有系统变量所以可以吧）。这个我要研究一下了

**Comment by yaumi123** [comment]
破案了。我是在启动了pycharm之后添加的ffmpeg环境变量，运行时os不会去读新的环境变量而是启动时就加载好了。重启解决问题。。

**Comment by papillon-unix** [comment]
Excuse-me, can you explain how did you fix it?

**Comment by papillon-unix** [comment]
I've the same problem again and again.

`segment set: |##################################################| 100.0% downloaded segments successfully!
2022-06-05 22:36:09,345 | INFO | decrypt and dump segments...
2022-06-05 22:36:09,389 | INFO | merging segments...
Traceback (most recent call last):
  File "get_tweet.py", line 54, in <module>
    m3u8_To_MP4.multithread_download(video)
  File "/home/pi/.local/lib/python3.7/site-packages/m3u8_To_MP4/__init__.py", line 95, in multithread_download
    crawler.fetch_mp4_by_m3u8_uri(True)
  File "/home/pi/.local/lib/python3.7/site-packages/m3u8_To_MP4/v2_abstract_crawler_processor.py", line 198, in fetch_mp4_by_m3u8_uri
    printer_helper.display_speed(task_start_time, fetch_end_time, task_end_time, self.mp4_file_path)
  File "/home/pi/.local/lib/python3.7/site-packages/m3u8_To_MP4/helpers/printer_helper.py", line 52, in display_speed
    download_speed = os.path.getsize(target_mp4_file_path) / download_time / 1024
  File "/usr/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: './m3u8_To_Mp4.mp4'`

**Comment by geekbunny2** [comment]
> I've the same problem again and again.
> 
> `segment set: |##################################################| 100.0% downloaded segments successfully! 2022-06-05 22:36:09,345 | INFO | decrypt and dump segments... 2022-06-05 22:36:09,389 | INFO | merging segments... Traceback (most recent call last): File "get_tweet.py", line 54, in <module> m3u8_To_MP4.multithread_download(video) File "/home/pi/.local/lib/python3.7/site-packages/m3u8_To_MP4/__init__.py", line 95, in multithread_download crawler.fetch_mp4_by_m3u8_uri(True) File "/home/pi/.local/lib/python3.7/site-packages/m3u8_To_MP4/v2_abstract_crawler_processor.py", line 198, in fetch_mp4_by_m3u8_uri printer_helper.display_speed(task_start_time, fetch_end_time, task_end_time, self.mp4_file_path) File "/home/pi/.local/lib/python3.7/site-packages/m3u8_To_MP4/helpers/printer_helper.py", line 52, in display_speed download_speed = os.path.getsize(target_mp4_file_path) / download_time / 1024 File "/usr/lib/python3.7/genericpath.py", line 50, in getsize return os.stat(filename).st_size FileNotFoundError: [Errno 2] No such file or directory: './m3u8_To_Mp4.mp4'`

@papillon-unix have you solved this problem? I'm running into the same issue

**Comment by xinxin8816** [comment]
说中文我反而看不懂了 :(

**Comment by yaumi123** [comment]
Install ffmpeg to your system then try it again!&nbsp;


杨肥肥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 上午9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [songs18/m3u8_To_MP4] Error: cannot find file (Issue #8)





  
I've the same problem again and again.
 
segment set: |##################################################| 100.0% downloaded segments successfully! 2022-06-05 22:36:09,345 | INFO | decrypt and dump segments... 2022-06-05 22:36:09,389 | INFO | merging segments... Traceback (most recent call last): File "get_tweet.py", line 54, in <module&gt; m3u8_To_MP4.multithread_download(video) File "/home/pi/.local/lib/python3.7/site-packages/m3u8_To_MP4/__init__.py", line 95, in multithread_download crawler.fetch_mp4_by_m3u8_uri(True) File "/home/pi/.local/lib/python3.7/site-packages/m3u8_To_MP4/v2_abstract_crawler_processor.py", line 198, in fetch_mp4_by_m3u8_uri printer_helper.display_speed(task_start_time, fetch_end_time, task_end_time, self.mp4_file_path) File "/home/pi/.local/lib/python3.7/site-packages/m3u8_To_MP4/helpers/printer_helper.py", line 52, in display_speed download_speed = os.path.getsize(target_mp4_file_path) / download_time / 1024 File "/usr/lib/python3.7/genericpath.py", line 50, in getsize return os.stat(filename).st_size FileNotFoundError: [Errno 2] No such file or directory: './m3u8_To_Mp4.mp4'
  
@papillon-unix have you solved this problem? I'm running into the same issue

**Comment by maciejbuchert** [comment]
I've installed ffmpeg on macOS
![image](https://user-images.githubusercontent.com/9607667/211541197-faf0a1aa-5e60-4c93-921a-e5bb1cdafc6b.png)

I've installed ffmpeg-python pacakge
![image](https://user-images.githubusercontent.com/9607667/211541424-a85d0715-7fcc-46ca-8d7c-a1f80dee754b.png)

Python version
![image](https://user-images.githubusercontent.com/9607667/211541622-f6ebe101-78a8-49be-858d-bc3d643783fb.png)

PIP version
![image](https://user-images.githubusercontent.com/9607667/211541554-9ff0025a-0348-45f3-9f9c-a427b98195ff.png)

and still has issues with `no such file or directory`. Any ideas?
